stripped name of invalid characters for edge
eligrey/FileSaver.js pull request #610
Opened 2019-11-28 17:46 UTC by botsteve

added the function that replaced all forbidden characters with '_'. This is the behaviour of the submit action on forms for Edge.

2020-05-06 17:47 UTC, StanciuMarian approved these changes

2020-05-07 01:46 UTC, eligrey requested changes
If Edge needs these changes then these changes should only be applied for the versions of Edge that need this.

2020-11-07 19:14 UTC, botsteve reviewed
finish adding required changes

2021-05-11 16:07 UTC, botsteve reviewed
finish implementing changes

2021-12-25 14:04 UTC, botsteve commented on src/FileSaver.js
> +function stripNameOfInvalidChars(name) {
Modified

2021-12-25 17:09 UTC, botsteve commented on src/FileSaver.js
> +function stripNameOfInvalidChars(name) {
added specific edge version for fix

2021-12-25 17:09 UTC, botsteve commented on src/FileSaver.js
> +function stripNameOfInvalidChars(name) {
@eligrey when you have time to review

2022-10-08 17:19 UTC, botsteve commented
Bump @eligrey @jimmywarting

2022-10-12 08:08 UTC, closed without merging